### ISSUE TITLE
open.mp fix

### ISSUE THREAD

**Issue by PainFrenemy2** [ziggi/rustext#11]
![4rMSpG8FJbk](https://github.com/user-attachments/assets/238cea4e-ddd7-4005-a24c-d88f43f201a6)

**Comment by ziggi** [comment]
Измени название rustext на любое другое.
И для openmp нужно использовать nomemhack версию (https://github.com/ziggi/rustext/releases)

**Comment by PainFrenemy2** [comment]
а исходники rustext nomemhack у вас остались?

**Comment by ziggi** [comment]
> а исходники rustext nomemhack у вас остались?

Они в отдельной ветке [nomemhack](https://github.com/ziggi/rustext/tree/nomemhack)
