### ISSUE TITLE
French support?

### ISSUE THREAD

**Issue by karimcambridge** [ziggi/rustext#2]
Is it possible?

Français looks like http://prntscr.com/dqqgaz in-game.

Edit: O, I just noticed this stuff isn't for client messages. Is there any fix for client messages?

**Comment by ziggi** [comment]
It's only for Text Draw's and GameText's.

> Edit: O, I just noticed this stuff isn't for client messages. Is there any fix for client messages?

SA-MP uses windows-1251 encoding, it's means that you should run SA-MP with French fonts. Or you can try to set French language on your Windows.

**Comment by karimcambridge** [comment]
Thanks.
