### ISSUE TITLE
Add Support for Arabic language and smiliars of UTF-8 languages...

### ISSUE THREAD

**Issue by Zorono** [ziggi/rustext#5]

**Comment by Zorono** [comment]
@ziggi it'd be great if you merged this repo into yours... (it supports Arabic and Farsi)
https://github.com/AmyrAhmady/FarsiType

https://gitlab.com/RcKoid/mod-s0beit-overlight/blob/master/bin/OverLight_Mod/OverLight_Settings.ini#L14

Edit: https://forum.sa-mp.com/showpost.php?p=1073428&postcount=3 :(

**Comment by ziggi** [comment]
Just add character codes for Arabic and Farsi fonts here: https://github.com/ziggi/rustext/blob/master/src/converter.cpp
I can't do this.
