### ISSUE TITLE
Не показывает форматируемую строку

### ISSUE THREAD

**Issue by Pe4en9** [ziggi/rustext#6]
При форматировании строки:
`format(str,sizeof(str),"%s",text);
PlayerTextDrawSetString(playerid, TD[playerid][0], str);`
И при условии что в text имеется пробел(где _ там пробел) `text="test_";` - ТД не отобразится в кириллице.

**Comment by ziggi** [comment]
Я так понимаю, это проблема стандартных TextDraw, она описана здесь: https://sampwiki.blast.hk/wiki/CreatePlayerTextDraw
> If you choose values for y that are less than 1, the first text row will be invisible and only the shadow is visible.
text[] must NOT be empty or the server will crash! If you need a textdraw that shows nothing, use " " (a space) or _ (underscore)
If the last character in the text is a space (" "), the text will all be blank.
If part of the text is off-screen, the color of the text will not show, only the shadow (if enabled) will.
