### ISSUE TITLE
support android and open mp

### ISSUE THREAD

**Issue by plakapenka** [ziggi/rustext#7]
support android and open mp

**Comment by ziggi** [comment]
- As I know Android version of GTA uses 1C version of the russifier, so the plugin should work well with it.
- I will consider porting to OMP after the public SDK release.

**Comment by kennytowN** [comment]
The transition to OMP is definitely needed, because your plugin helps to work with Russian-language text.

**Comment by eakwarp** [comment]
> * As I know Android version of GTA uses 1C version of the russifier, so the plugin should work well with it.
> * I will consider porting to OMP after the public SDK release.

sdk released :)

**Comment by ziggi** [comment]
open.mp is supported in nomemhack version of the plugin: https://github.com/ziggi/rustext/releases
