### ISSUE TITLE
Support for open mp

### ISSUE THREAD

**Issue by nazpol9** [ziggi/rustext#9]
Hi,

When will there be a rustext version compatible with open mp?

Thanks.

**Comment by ziggi** [comment]
[This one](https://github.com/ziggi/rustext/releases/tag/v1.2.0) should work fine

**Comment by nazpol9** [comment]
> [This one](https://github.com/ziggi/rustext/releases/tag/v1.2.0) should work fine

Thanks for your reply.

Unfortunately, the open.mp skips this plugin with the next error in console:
![image](https://github.com/ziggi/rustext/assets/61046385/b1656181-1f72-4916-870a-1c7635431b23)

I appreciate any help you can provide.

**Comment by ziggi** [comment]
Try to change the name of the file. For example rename `rustext.so` to `rustext2.so`

**Comment by nazpol9** [comment]
> Try to change the name of the file. For example rename `rustext.so` to `rustext2.so`

It works, thank you for your fast reply!

**Comment by ghost** [comment]
пожалуйста, если можно, сделайте бэкпорт исправлений из более новых версий (2.0, те, что с memhack) в 1.2.0 и выпустите ее как omp-совместимую.

Потому что TextDrawSetString не работает, и еще что-то там.

**Comment by ziggi** [comment]
> Потому что TextDrawSetString не работает, и еще что-то там.

@ghost Должно работать. Покажи, что там не работает.

**Comment by ziggi** [comment]
Added a nomemhack version of the plugin with some backported functions from 2.0.8: https://github.com/ziggi/rustext/releases

Добавил nomemhack версию плагина с функциями из 2.0.8: https://github.com/ziggi/rustext/releases
